import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";

export default async function StudentDashboard(){
  const sb=await createClient(); const {data:c}=await sb.auth.getClaims(); const uid=c?.claims?.sub; if(!uid)redirect("/student-login");
  const {data:s}=await sb.from("students").select("id,name,admission_no,school_id,class_name,section,class_id,section_id,status").eq("user_id",uid).maybeSingle();
  if(!s)return <main className="content"><div className="card"><h1>Student profile not linked</h1></div></main>;
  const [{data:school},{data:att},{data:fees},{data:homework},{data:reports},{data:timetable},{data:notices},{data:notifications},{data:leaves}]=await Promise.all([
    sb.from("schools").select("name").eq("id",s.school_id).single(),
    sb.from("student_attendance").select("attendance_date,status").eq("student_id",s.id).order("attendance_date",{ascending:false}).limit(30),
    sb.from("student_fees").select("description,amount,discount,due_date,status").eq("student_id",s.id).order("due_date",{ascending:false}).limit(20),
    sb.from("homework").select("id,title,description,due_date,status,class_id,section_id").eq("school_id",s.school_id).eq("class_id",s.class_id).order("due_date",{ascending:false}).limit(10),
    sb.from("report_cards").select("exam_id,total_marks,max_marks,percentage,overall_grade,remarks,status").eq("student_id",s.id).order("created_at",{ascending:false}).limit(10),
    sb.from("timetables").select("day_of_week,period_no,start_time,end_time,room,status").eq("school_id",s.school_id).eq("class_id",s.class_id).eq("section_id",s.section_id).eq("status","active").order("day_of_week").order("period_no"),
    sb.from("notices").select("id,title,content,publish_date").eq("school_id",s.school_id).eq("status","published").order("publish_date",{ascending:false}).limit(10),
    sb.from("notifications").select("id,title,message,notification_type,created_at").eq("school_id",s.school_id).eq("status","published").order("created_at",{ascending:false}).limit(10),
    sb.from("leave_requests").select("leave_type,start_date,end_date,status,reason").eq("school_id",s.school_id).eq("requester_type","student").eq("requester_id",s.id).order("created_at",{ascending:false}).limit(10)
  ]);
  const present=(att??[]).filter(a=>a.status==="present"||a.status==="late").length;
  const billed=(fees??[]).reduce((n,f)=>n+Number(f.amount||0)-Number(f.discount||0),0);
  return <div className="shell"><aside className="sidebar"><div className="brand">🎓 SchoolConnect</div><div className="nav"><a className="active" href="/dashboard/student">Home</a><a href="/dashboard/student#attendance">Attendance</a><a href="/dashboard/student#fees">Fees</a><a href="/dashboard/student#homework">Homework</a><a href="/dashboard/student#results">Results</a><a href="/dashboard/student#timetable">Timetable</a><a href="/dashboard/student#notices">Notices</a><a href="/dashboard/student#communication">Communication</a><a href="/dashboard/student#leave">Leave</a></div></aside><main className="main"><header className="top"><strong>{school?.name??"School"}</strong><span className="muted">Student · {s.name}</span></header><section className="content"><div className="hero"><div><h1>Hello, {s.name}</h1><p className="muted">{s.admission_no??"Student"} · {s.class_name??"Class"} {s.section??""}</p></div><span className="badge">Live · Supabase</span></div><div className="cards"><div className="card"><div className="label">Recent Attendance</div><div className="value">{present}</div></div><div className="card"><div className="label">Fee Items</div><div className="value">{fees?.length??0}</div></div><div className="card"><div className="label">Fee Billed</div><div className="value">₹{billed.toLocaleString("en-IN")}</div></div><div className="card"><div className="label">Homework</div><div className="value">{homework?.length??0}</div></div></div>
  <div id="attendance" className="card" style={{marginTop:16}}><h2>Attendance</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Status</th></tr></thead><tbody>{(att??[]).map((a,i)=><tr key={i}><td>{a.attendance_date}</td><td><span className="badge">{a.status}</span></td></tr>)}</tbody></table></div></div>
  <div id="fees" className="card" style={{marginTop:16}}><h2>Fees</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>Description</th><th>Amount</th><th>Due</th><th>Status</th></tr></thead><tbody>{(fees??[]).map((f,i)=><tr key={i}><td>{f.description??"Fee"}</td><td>₹{Number(f.amount||0).toLocaleString("en-IN")}</td><td>{f.due_date??"—"}</td><td><span className="badge">{f.status}</span></td></tr>)}</tbody></table></div></div>
  <div id="homework" className="card" style={{marginTop:16}}><h2>Homework</h2>{(homework??[]).map(h=><div className="row" key={h.id}><div><strong>{h.title}</strong><div className="muted">{h.description??""} · Due {h.due_date??"—"}</div></div><span className="badge">{h.status}</span></div>)}</div>
  <div id="results" className="card" style={{marginTop:16}}><h2>Results & Report Cards</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>Total</th><th>Percentage</th><th>Grade</th><th>Status</th></tr></thead><tbody>{(reports??[]).map((r,i)=><tr key={i}><td>{r.total_marks}/{r.max_marks}</td><td>{r.percentage??"—"}%</td><td>{r.overall_grade??"—"}</td><td>{r.status}</td></tr>)}</tbody></table></div></div>
  <div id="timetable" className="card" style={{marginTop:16}}><h2>Timetable</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>Day</th><th>Period</th><th>Time</th><th>Room</th></tr></thead><tbody>{(timetable??[]).map((t,i)=><tr key={i}><td>{["","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][t.day_of_week]??t.day_of_week}</td><td>{t.period_no}</td><td>{String(t.start_time).slice(0,5)}–{String(t.end_time).slice(0,5)}</td><td>{t.room??"—"}</td></tr>)}</tbody></table></div></div>
  <div id="notices" className="card" style={{marginTop:16}}><h2>Notices</h2>{(notices??[]).map(n=><div className="row" key={n.id}><div><strong>{n.title}</strong><div className="muted">{n.content}</div></div><span>{n.publish_date}</span></div>)}</div>
  <div id="communication" className="card" style={{marginTop:16}}><h2>Communication</h2>{(notifications??[]).map(n=><div className="row" key={n.id}><div><strong>{n.title}</strong><div className="muted">{n.message}</div></div><span className="badge">{n.notification_type}</span></div>)}{!(notifications??[]).length&&<p className="muted">No new notifications.</p>}</div>
  <div id="leave" className="card" style={{marginTop:16}}><h2>Leave</h2>{(leaves??[]).map((l,i)=><div className="row" key={i}><div><strong>{l.leave_type}</strong><div className="muted">{l.start_date} to {l.end_date} · {l.reason??""}</div></div><span className="badge">{l.status}</span></div>)}{!(leaves??[]).length&&<p className="muted">No leave requests found.</p>}</div>
 </section></main></div>;
}