import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import StaffManagementClient from "@/components/staff-management-client";

export default async function StaffPage(){
 const supabase=await createClient(); const {data:claimsData}=await supabase.auth.getClaims(); if(!claimsData?.claims?.sub)redirect("/login"); const userId=claimsData.claims.sub;
 const {data:membership}=await supabase.from("school_users").select("school_id,display_name").eq("user_id",userId).eq("is_active",true).not("school_id","is",null).limit(1).maybeSingle(); if(!membership?.school_id)return <main className="content"><div className="card"><h1>School access is not configured</h1></div></main>;
 const schoolId=membership.school_id; const [{data:school},{data:staff}]=await Promise.all([supabase.from("schools").select("name").eq("id",schoolId).single(),supabase.from("staff").select("id,employee_no,name,designation,department,phone,email,joining_date,status").eq("school_id",schoolId).order("employee_no",{ascending:true,nullsFirst:false})]);
 const nav=[["Dashboard","/dashboard"],["Students","/dashboard/students"],["Parents","/dashboard/parents"],["Teachers & Staff","/dashboard/staff"],["Admissions","/dashboard/admissions"],["Attendance","/dashboard/attendance"],["Fees","/dashboard/fees"],["Academics","/dashboard/academics"],["Timetable","/dashboard/timetable"],["Homework","/dashboard/homework"],["Exams & Results","/dashboard/exams"],["Notices & Events","/dashboard/notices"],["Communication","/dashboard/communication"],["Reports","/dashboard/reports"],["Leave Management","/dashboard/leave"],["Settings","/dashboard/settings"]];
 return <div className="shell"><aside className="sidebar"><div className="brand">🎓 SchoolConnect</div><div className="nav">{nav.map(([n,h])=><a className={n==="Teachers & Staff"?"active":""} href={h} key={n}>{n}</a>)}</div></aside><main className="main"><header className="top"><strong>{school?.name??"School"}</strong><span className="muted">School Admin · {membership.display_name??"Admin"}</span></header><section className="content"><div className="hero"><div><h1>Teachers & Staff</h1><p className="muted">Manage staff records and keep the school directory current.</p></div><span className="badge">Live · Supabase</span></div><StaffManagementClient schoolId={schoolId} initialStaff={staff??[]}/></section></main></div>;
}
