import React,{useEffect,useState}from"react";import{SafeAreaView,View,Text,TextInput,TouchableOpacity,StyleSheet,ScrollView,Alert}from"react-native";import{createClient,Session}from"@supabase/supabase-js";
const sb=createClient(process.env.EXPO_PUBLIC_SUPABASE_URL||"",process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"");
const modulesByRole:any={parent:["Children","Attendance","Fees","Homework","Results","Timetable","Notices","Leave","Communication"],student:["Attendance","Fees","Homework","Results","Timetable","Notices","Leave","Communication"],teacher:["My Classes","Attendance","Homework","Exams & Results","Timetable","Leave","Communication"],school_admin:["Students","Parents","Teachers & Staff","Admissions","Attendance","Fees","Academics","Homework","Exams","Timetable","Notices","Reports","Communication","Documents","Settings"],super_admin:["Schools","Subscriptions","Audit","Platform Settings"]};
export default function App(){
 const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[session,setSession]=useState<Session|null>(null),[role,setRole]=useState("user"),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{sb.auth.getSession().then(async({data})=>{if(data.session){setSession(data.session);await loadRole(data.session.user.id)}});const{data}=sb.auth.onAuthStateChange(async(_e,s)=>{setSession(s);if(s)await loadRole(s.user.id);else setRole("user")});return()=>data.subscription.unsubscribe()},[]);
 async function loadRole(uid:string){const{data}=await sb.from("user_roles").select("role_id").eq("user_id",uid).limit(1).maybeSingle();if(!data?.role_id){setRole("user");return}const{data:r}=await sb.from("roles").select("name").eq("id",data.role_id).maybeSingle();setRole(r?.name||"user")}
 async function login(){setBusy(true);setError("");const{data,error}=await sb.auth.signInWithPassword({email,password});if(error)setError(error.message);else if(data.session){setSession(data.session);await loadRole(data.session.user.id)}setBusy(false)}
 async function signOut(){await sb.auth.signOut();setSession(null);setRole("user")}
 if(!session)return <SafeAreaView style={s.safe}><View style={s.card}><Text style={s.logo}>🎓</Text><Text style={s.title}>SchoolConnect</Text><Text style={s.muted}>Secure mobile school portal</Text><TextInput style={s.input} placeholder="Email" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail}/><TextInput style={s.input} placeholder="Password" secureTextEntry value={password} onChangeText={setPassword}/>{error?<Text style={s.error}>{error}</Text>:null}<TouchableOpacity style={s.button} onPress={login} disabled={busy}><Text style={s.buttonText}>{busy?"Signing in…":"Sign in"}</Text></TouchableOpacity></View></SafeAreaView>;
 const modules=modulesByRole[role]||modulesByRole.student;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.scroll}><Text style={s.title}>SchoolConnect</Text><Text style={s.muted}>{session.user.email} · {role.replace("_"," ")}</Text><View style={s.grid}>{modules.map((x:string)=><TouchableOpacity style={s.tile} key={x} onPress={()=>Alert.alert(x,"This module is connected to the SchoolConnect platform and will use your account permissions.")}><Text style={s.tileText}>{x}</Text><Text style={s.tileSub}>Open module ›</Text></TouchableOpacity>)}</View><TouchableOpacity style={s.button} onPress={signOut}><Text style={s.buttonText}>Sign out</Text></TouchableOpacity></ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#F7F9FC"},scroll:{padding:20},card:{margin:20,padding:24,borderRadius:18,backgroundColor:"#fff",marginTop:80},logo:{fontSize:44,textAlign:"center"},title:{fontSize:28,fontWeight:"700",color:"#173B63",marginBottom:6},muted:{color:"#667085",marginBottom:20},input:{borderWidth:1,borderColor:"#D0D5DD",borderRadius:12,padding:14,marginBottom:12,fontSize:16,backgroundColor:"#fff"},button:{backgroundColor:"#245EA8",padding:15,borderRadius:12,alignItems:"center",marginTop:8},buttonText:{color:"#fff",fontWeight:"700",fontSize:16},error:{color:"#D64545",marginBottom:10},grid:{flexDirection:"row",flexWrap:"wrap",gap:12,marginVertical:20},tile:{width:"47%",minHeight:100,borderRadius:16,backgroundColor:"#fff",padding:18,justifyContent:"center",borderWidth:1,borderColor:"#E4E7EC"},tileText:{fontWeight:"700",color:"#172033",fontSize:15},tileSub:{color:"#667085",marginTop:8,fontSize:12}});
