import {createClient} from "@/lib/supabase/server";
import {redirect} from "next/navigation";
import UserRoleClient from "@/components/user-role-client";
export default async function UsersPage(){const supabase=await createClient();const {data:claimsData}=await supabase.auth.getClaims();if(!claimsData?.claims?.sub)redirect("/login");const userId=claimsData.claims.sub;const {data:membership}=await supabase.from("school_users").select("school_id,display_name").eq("user_id",userId).eq("is_active",true).not("school_id","is",null).limit(1).maybeSingle();if(!membership?.school_id)return <main className="content"><div className="card"><h1>School access is not configured</h1></div></main>;const schoolId=membership.school_id;const {data:school}=await supabase.from("schools").select("name").eq("id",schoolId).single();
const {data:schoolUsers}=await supabase.from("school_users").select("user_id,display_name,is_active").eq("school_id",schoolId).order("display_name");
const {data:userRoles}=await supabase.from("user_roles").select("user_id,role_id").eq("school_id",schoolId);
const {data:roles}=await supabase.from("roles").select("id,name,description").neq("name","super_admin").order("name");
const roleMap=new Map((userRoles??[]).map((r:any)=>[r.user_id,r.role_id]));
const roleById=new Map((roles??[]).map((r:any)=>[r.id,r]));
const normalized=(schoolUsers??[]).map((u:any)=>{const roleId=roleMap.get(u.user_id)??null;const r=roleId?roleById.get(roleId):null;return {user_id:u.user_id,display_name:u.display_name,is_active:u.is_active,role_id:roleId,role_name:r?.name??null,role_desc:r?.description??null}});
 const nav=["Dashboard","Students","Parents","Teachers & Staff","Admissions","Attendance","Fees","Academics","Timetable","Homework","Exams & Results","Notices & Events","Communication","Reports","Leave Management","Users & Roles","Settings"];const hrefs=["/dashboard","/dashboard/students","/dashboard/parents","/dashboard/staff","/dashboard/admissions","/dashboard/attendance","/dashboard/fees","/dashboard/academics","/dashboard/timetable","/dashboard/homework","/dashboard/exams","/dashboard/notices","/dashboard/communication","/dashboard/reports","/dashboard/leave","/dashboard/users","/dashboard/settings"];return <div className="shell"><aside className="sidebar"><div className="brand">🎓 SchoolConnect</div><div className="nav">{nav.map((n,i)=><a className={n==="Users & Roles"?"active":""} href={hrefs[i]} key={n}>{n}</a>)}</div></aside><main className="main"><header className="top"><strong>{school?.name??"School"}</strong><span className="muted">School Admin · {membership.display_name??"Admin"}</span></header><section className="content"><div className="hero"><div><h1>Users & Roles</h1><p className="muted">Control school account access and role assignment.</p></div><span className="badge">Live · Supabase</span></div><UserRoleClient schoolId={schoolId} initialUsers={normalized} roles={roles??[]} currentUserId={userId}/></section></main></div>}
