"use client";
import { useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Enquiry={id:string;enquiry_no:string;student_name:string;class_interested:string|null;parent_name:string|null;parent_phone:string|null;source:string|null;status:string;next_follow_up_at:string|null;notes:string|null};
type App={id:string;application_no:string;student_name:string;class_applied:string|null;parent_name:string|null;parent_phone:string|null;status:string;enquiry_id:string|null};

const stages=["enquiry","contacted","interested","visit_scheduled","application_started","application_submitted","document_verification","entrance_test","approved","fee_pending","admitted","lost","future_follow_up"];
const appStages=["draft","submitted","document_verification","entrance_test","approved","fee_pending","admitted","rejected"];

export default function AdmissionsClient({schoolId,initial,initialApps}:{schoolId:string;initial:Enquiry[];initialApps:App[]}) {
 const [rows,setRows]=useState(initial),[apps,setApps]=useState(initialApps),[tab,setTab]=useState<"enquiries"|"applications">("enquiries");
 const [open,setOpen]=useState(false),[saving,setSaving]=useState(false),[filter,setFilter]=useState("all"),[q,setQ]=useState(""),[message,setMessage]=useState("");
 const [form,setForm]=useState({student_name:"",class_interested:"",parent_name:"",parent_phone:"",parent_email:"",source:"website",status:"enquiry",notes:""});
 const filtered=useMemo(()=>rows.filter(r=>(filter==="all"||r.status===filter)&&(!q||[r.student_name,r.parent_name,r.parent_phone,r.enquiry_no].join(" ").toLowerCase().includes(q.toLowerCase()))),[rows,filter,q]);
 const counts=stages.reduce((m,s)=>(m[s]=rows.filter(r=>r.status===s).length,m),{} as Record<string,number>);
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage("");const supabase=createClient();const enquiry_no="ENQ-"+new Date().getFullYear()+"-"+String(rows.length+1).padStart(3,"0");const {data,error}=await supabase.from("admission_enquiries").insert({...form,school_id:schoolId,enquiry_no}).select("id,enquiry_no,student_name,class_interested,parent_name,parent_phone,source,status,next_follow_up_at,notes").single();if(error)setMessage(error.message);else{setRows([data,...rows]);setOpen(false);setForm({student_name:"",class_interested:"",parent_name:"",parent_phone:"",parent_email:"",source:"website",status:"enquiry",notes:""});setMessage("Enquiry added successfully.")}setSaving(false)}
 async function updateEnquiry(id:string,status:string){const supabase=createClient();const {error}=await supabase.from("admission_enquiries").update({status,updated_at:new Date().toISOString()}).eq("id",id).eq("school_id",schoolId);if(error)setMessage(error.message);else setRows(rows.map(r=>r.id===id?{...r,status}:r))}
 async function createApplication(r:Enquiry){const supabase=createClient();const application_no="APP-"+new Date().getFullYear()+"-"+String(apps.length+1).padStart(3,"0");const {data,error}=await supabase.from("admission_applications").insert({school_id:schoolId,enquiry_id:r.id,application_no,student_name:r.student_name,class_applied:r.class_interested,parent_name:r.parent_name,parent_phone:r.parent_phone,status:"submitted"}).select("id,application_no,student_name,class_applied,parent_name,parent_phone,status,enquiry_id").single();if(error)setMessage(error.message);else{setApps([data,...apps]);await updateEnquiry(r.id,"application_submitted");setTab("applications");setMessage("Application created successfully.")}}
 async function updateApp(id:string,status:string){const supabase=createClient();const {error}=await supabase.from("admission_applications").update({status,updated_at:new Date().toISOString()}).eq("id",id).eq("school_id",schoolId);if(error)setMessage(error.message);else setApps(apps.map(a=>a.id===id?{...a,status}:a))}
 async function admit(id:string){const supabase=createClient();const {data,error}=await supabase.rpc("admit_application",{p_application_id:id,p_class_name:null,p_section:null});if(error)setMessage(error.message);else{setApps(apps.map(a=>a.id===id?{...a,status:"admitted"}:a));setMessage("Student admitted successfully and added to Students.");}}
 return <div>{message&&<div className="success">{message}</div>}
 <div className="cards" style={{gridTemplateColumns:"repeat(4,1fr)",marginBottom:16}}>{[["Total Enquiries",rows.length],["Active Pipeline",rows.filter(r=>!["lost","admitted"].includes(r.status)).length],["Applications",apps.length],["Admitted",counts.admitted||0]].map(([a,b])=><div className="card" key={String(a)}><div className="label">{a}</div><div className="value">{b}</div></div>)}</div>
 <div className="card">
  <div style={{display:"flex",gap:8,marginBottom:18}}><button onClick={()=>setTab("enquiries")} style={{padding:"10px 14px",border:0,borderRadius:9,background:tab==="enquiries"?"#173b63":"#eef2f6",color:tab==="enquiries"?"#fff":"#172033",fontWeight:700}}>Enquiries</button><button onClick={()=>setTab("applications")} style={{padding:"10px 14px",border:0,borderRadius:9,background:tab==="applications"?"#173b63":"#eef2f6",color:tab==="applications"?"#fff":"#172033",fontWeight:700}}>Applications</button></div>
  {tab==="enquiries"?<><div style={{display:"flex",gap:10,flexWrap:"wrap",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><input placeholder="Search student, parent, phone..." value={q} onChange={e=>setQ(e.target.value)} style={{padding:11,border:"1px solid #d9e0e8",borderRadius:10,minWidth:220}}/><select value={filter} onChange={e=>setFilter(e.target.value)} style={{padding:11,border:"1px solid #d9e0e8",borderRadius:10}}><option value="all">All stages</option>{stages.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></div><button onClick={()=>setOpen(true)} style={{padding:"11px 16px",border:0,borderRadius:10,background:"#173b63",color:"#fff",fontWeight:700}}>+ New Enquiry</button></div>
  <div style={{overflowX:"auto"}}><table className="data-table"><thead><tr><th>Enquiry</th><th>Student</th><th>Parent</th><th>Class</th><th>Stage</th><th>Action</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.enquiry_no}</td><td><strong>{r.student_name}</strong><div className="muted">{r.parent_phone??""}</div></td><td>{r.parent_name??"—"}</td><td>{r.class_interested??"—"}</td><td><select value={r.status} onChange={e=>updateEnquiry(r.id,e.target.value)} style={{padding:7,border:"1px solid #d9e0e8",borderRadius:8}}>{stages.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></td><td>{["application_submitted","approved","fee_pending","admitted"].includes(r.status)?<button onClick={()=>createApplication(r)} style={{padding:7,border:0,borderRadius:7,background:"#eef4fb"}}>Create App</button>:<button onClick={()=>setMessage(r.notes||"No notes")} style={{border:0,background:"transparent"}}>View</button>}</td></tr>)}</tbody></table></div></>:<div style={{overflowX:"auto"}}><table className="data-table"><thead><tr><th>Application</th><th>Student</th><th>Class</th><th>Parent</th><th>Status</th><th>Action</th></tr></thead><tbody>{apps.map(a=><tr key={a.id}><td>{a.application_no}</td><td><strong>{a.student_name}</strong></td><td>{a.class_applied??"—"}</td><td>{a.parent_name??"—"}<div className="muted">{a.parent_phone??""}</div></td><td><select value={a.status} onChange={e=>updateApp(a.id,e.target.value)} style={{padding:7,border:"1px solid #d9e0e8",borderRadius:8}}>{appStages.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></td><td>{["approved","fee_pending"].includes(a.status)&&<button onClick={()=>admit(a.id)} style={{padding:7,border:0,borderRadius:7,background:"#e8f6ef",fontWeight:700}}>Admit Student</button>}{a.status==="admitted"&&<span className="badge">Admitted</span>}</td></tr>)}</tbody></table></div>}
 </div>
 {open&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.35)",display:"grid",placeItems:"center",padding:20,zIndex:100}}><form onSubmit={save} className="card" style={{width:"min(720px,100%)",maxHeight:"90vh",overflowY:"auto"}}><div style={{display:"flex",justifyContent:"space-between"}}><h2>New Admission Enquiry</h2><button type="button" onClick={()=>setOpen(false)}>✕</button></div><div className="cards" style={{gridTemplateColumns:"repeat(2,1fr)"}}>{[["student_name","Student name *"],["class_interested","Class interested"],["parent_name","Parent / guardian"],["parent_phone","Parent phone"],["parent_email","Parent email"],["source","Source"]].map(([k,l])=><label key={k} style={{display:"grid",gap:6,fontWeight:600,fontSize:14}}>{l}<input required={k==="student_name"} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} style={{padding:11,border:"1px solid #d9e0e8",borderRadius:10}}/></label>)}</div><label style={{display:"grid",gap:6,marginTop:14,fontWeight:600,fontSize:14}}>Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows={4} style={{padding:11,border:"1px solid #d9e0e8",borderRadius:10}}/></label><button disabled={saving} style={{marginTop:16,padding:13,border:0,borderRadius:10,background:"#173b63",color:"#fff",fontWeight:700,width:"100%"}}>{saving?"Saving...":"Create Enquiry"}</button></form></div>}
 </div>;
}