"use client";

import { useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type StaffRow={id:string;employee_no:string|null;name:string;designation:string|null;department:string|null;phone:string|null;email:string|null;joining_date:string|null;status:string};
const emptyForm={employee_no:"",name:"",designation:"Teacher",department:"",phone:"",email:"",joining_date:"",status:"active"};

export default function StaffManagementClient({schoolId,initialStaff}:{schoolId:string;initialStaff:StaffRow[]}){
 const supabase=createClient(); const [rows,setRows]=useState(initialStaff); const [form,setForm]=useState({...emptyForm}); const [editingId,setEditingId]=useState<string|null>(null); const [query,setQuery]=useState(""); const [status,setStatus]=useState("all"); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState("");
 const filtered=useMemo(()=>rows.filter(r=>{const hay=[r.name,r.employee_no,r.designation,r.department,r.phone,r.email].join(" ").toLowerCase();return (!query||hay.includes(query.toLowerCase()))&&(status==="all"||r.status===status)}),[rows,query,status]);
 const reset=()=>{setForm({...emptyForm});setEditingId(null)};
 const edit=(r:StaffRow)=>{setEditingId(r.id);setForm({employee_no:r.employee_no||"",name:r.name,designation:r.designation||"",department:r.department||"",phone:r.phone||"",email:r.email||"",joining_date:r.joining_date||"",status:r.status});window.scrollTo({top:0,behavior:"smooth"})};
 async function save(){if(!form.name.trim()){setMsg("Staff name is required.");return} setSaving(true);setMsg(""); const payload={school_id:schoolId,employee_no:form.employee_no.trim()||null,name:form.name.trim(),designation:form.designation.trim()||null,department:form.department.trim()||null,phone:form.phone.trim()||null,email:form.email.trim()||null,joining_date:form.joining_date||null,status:form.status}; const result=editingId?await supabase.from("staff").update(payload).eq("id",editingId).select("id,employee_no,name,designation,department,phone,email,joining_date,status").single():await supabase.from("staff").insert(payload).select("id,employee_no,name,designation,department,phone,email,joining_date,status").single(); if(result.error){setSaving(false);setMsg("Could not save staff: "+result.error.message);return} setRows(prev=>editingId?prev.map(x=>x.id===editingId?result.data:x):[result.data,...prev]);reset();setSaving(false);setMsg("Staff record saved successfully.")}
 async function toggle(r:StaffRow){const next=r.status==="active"?"inactive":"active";const {data,error}=await supabase.from("staff").update({status:next}).eq("id",r.id).select("id,employee_no,name,designation,department,phone,email,joining_date,status").single();if(error){setMsg("Could not update status: "+error.message);return}setRows(prev=>prev.map(x=>x.id===r.id?data:x));setMsg(r.name+" is now "+next+".")}
 const active=rows.filter(r=>r.status==="active").length; const teachers=rows.filter(r=>String(r.designation||"").toLowerCase().includes("teacher")&&r.status==="active").length;
 return <div><div className="cards"><div className="card"><div className="label">Total Staff</div><div className="value">{rows.length}</div></div><div className="card"><div className="label">Active Staff</div><div className="value">{active}</div></div><div className="card"><div className="label">Teachers</div><div className="value">{teachers}</div></div><div className="card"><div className="label">Inactive</div><div className="value">{rows.length-active}</div></div></div>
 <div className="card" style={{marginTop:16}}><div className="hero" style={{marginBottom:16}}><div><h2>{editingId?"Edit Staff":"Add Staff Member"}</h2><p className="muted">Maintain the school staff directory.</p></div>{editingId&&<button className="button" onClick={reset}>Cancel Edit</button>}</div><div className="form-grid">
 {[["Employee No.","employee_no"],["Name *","name"],["Designation","designation"],["Department","department"],["Phone","phone"],["Email","email"],["Joining Date","joining_date"]].map(([label,key])=><label className="field" key={key}><span>{label}</span><input type={key==="joining_date"?"date":"text"} value={(form as any)[key]} onChange={e=>setForm(x=>({...x,[key]:e.target.value}))}/></label>)}
 <label className="field"><span>Status</span><select value={form.status} onChange={e=>setForm(x=>({...x,status:e.target.value}))}><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div><div className="settings-actions"><button className="button primary" disabled={saving} onClick={save}>{saving?"Saving...":editingId?"Update Staff":"Add Staff"}</button>{msg&&<span className="save-message">{msg}</span>}</div></div>
 <div className="card" style={{marginTop:16,overflowX:"auto"}}><div className="hero" style={{marginBottom:12}}><div><h2>Staff Directory</h2><p className="muted">Search, edit and activate or deactivate staff.</p></div></div><div className="toolbar"><input placeholder="Search staff..." value={query} onChange={e=>setQuery(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All Status</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div><table className="data-table"><thead><tr><th>Staff</th><th>Employee No.</th><th>Designation</th><th>Department</th><th>Contact</th><th>Joining</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong>{r.name}</strong><div className="muted">{r.email||"—"}</div></td><td>{r.employee_no||"—"}</td><td>{r.designation||"—"}</td><td>{r.department||"—"}</td><td>{r.phone||"—"}</td><td>{r.joining_date||"—"}</td><td><span className="badge">{r.status}</span></td><td><button className="button" onClick={()=>edit(r)}>Edit</button>{" "}<button className="button" onClick={()=>toggle(r)}>{r.status==="active"?"Deactivate":"Activate"}</button></td></tr>)}</tbody></table>{!filtered.length&&<p className="muted">No staff records match your filters.</p>}</div></div>;
}
