"use client";

import { useMemo, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type StaffRow={id:string;employee_no:string|null;name:string;designation:string|null;department:string|null;phone:string|null;email:string|null;joining_date:string|null;status:string};
const emptyForm={employee_no:"",name:"",designation:"Teacher",department:"",phone:"",email:"",joining_date:"",status:"active"};

export default function StaffManagementClient({schoolId,initialStaff}:{schoolId:string;initialStaff:StaffRow[]}){
 const supabase=createClient(); const fileRef=useRef<HTMLInputElement>(null); const [rows,setRows]=useState(initialStaff); const [form,setForm]=useState({...emptyForm}); const [editingId,setEditingId]=useState<string|null>(null); const [query,setQuery]=useState(""); const [status,setStatus]=useState("all"); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState("");
 const filtered=useMemo(()=>rows.filter(r=>{const hay=[r.name,r.employee_no,r.designation,r.department,r.phone,r.email].join(" ").toLowerCase();return (!query||hay.includes(query.toLowerCase()))&&(status==="all"||r.status===status)}),[rows,query,status]);
 const reset=()=>{setForm({...emptyForm});setEditingId(null)};
 const edit=(r:StaffRow)=>{setEditingId(r.id);setForm({employee_no:r.employee_no||"",name:r.name,designation:r.designation||"",department:r.department||"",phone:r.phone||"",email:r.email||"",joining_date:r.joining_date||"",status:r.status});window.scrollTo({top:0,behavior:"smooth"})};
 async function save(){if(!form.name.trim()){setMsg("Staff name is required.");return} setSaving(true);setMsg(""); const payload={school_id:schoolId,employee_no:form.employee_no.trim()||null,name:form.name.trim(),designation:form.designation.trim()||null,department:form.department.trim()||null,phone:form.phone.trim()||null,email:form.email.trim()||null,joining_date:form.joining_date||null,status:form.status}; const result=editingId?await supabase.from("staff").update(payload).eq("id",editingId).select("id,employee_no,name,designation,department,phone,email,joining_date,status").single():await supabase.from("staff").insert(payload).select("id,employee_no,name,designation,department,phone,email,joining_date,status").single(); if(result.error){setSaving(false);setMsg("Could not save staff: "+result.error.message);return} setRows(prev=>editingId?prev.map(x=>x.id===editingId?result.data:x):[result.data,...prev]);reset();setSaving(false);setMsg("Staff record saved successfully.")}

 function downloadTemplate(){const csv="Employee No.,Name,Designation,Department,Phone,Email,Joining Date,Status\\nEMP013,Example Staff,Teacher,Academics,9876543210,example@school.com,2026-04-01,active\\n";const blob=new Blob([csv],{type:"text/csv;charset=utf-8;"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="staff_import_template.csv";a.click();URL.revokeObjectURL(url)}
 function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[];let cell="";let quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'){if(quoted&&next==='"'){cell+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){row.push(cell.trim());cell="";}else if((ch==='\\n'||ch==='\\r')&&!quoted){if(ch==='\\r'&&next==='\\n')i++;row.push(cell.trim());cell="";if(row.some(x=>x!==""))rows.push(row);row=[];}else cell+=ch;}if(cell!==""||row.length){row.push(cell.trim());if(row.some(x=>x!==""))rows.push(row);}return rows}
 async function importStaff(file:File){setSaving(true);setMsg("");try{const text=await file.text();const parsed=parseCsv(text);if(parsed.length<2)throw new Error("CSV is empty or has no staff rows.");const headers=parsed[0].map(x=>x.toLowerCase().replace(/[^a-z0-9]+/g,"_"));const required=["employee_no","name"];if(required.some(x=>!headers.includes(x)))throw new Error("Template headers required: Employee No. and Name.");const idx=(name:string)=>headers.indexOf(name);const existing=new Set(rows.map(r=>String(r.employee_no||"").trim().toLowerCase()).filter(Boolean));const batchKeys=new Set<string>();const payloads:any[]=[];for(let i=1;i<parsed.length;i++){const r=parsed[i];const get=(h:string)=>idx(h)>=0?(r[idx(h)]||"").trim():"";const employee_no=get("employee_no");const name=get("name");if(!employee_no&&!name)continue;if(!name)throw new Error("Row "+(i+1)+": Name is required.");if(!employee_no)throw new Error("Row "+(i+1)+": Employee No. is required.");const key=employee_no.toLowerCase();if(existing.has(key)||batchKeys.has(key))throw new Error("Row "+(i+1)+": duplicate Employee No. "+employee_no);batchKeys.add(key);const status=(get("status")||"active").toLowerCase();if(status!=="active"&&status!=="inactive")throw new Error("Row "+(i+1)+": Status must be active or inactive.");payloads.push({school_id:schoolId,employee_no,name,designation:get("designation")||null,department:get("department")||null,phone:get("phone")||null,email:get("email")||null,joining_date:get("joining_date")||null,status})}if(!payloads.length)throw new Error("No valid staff rows found.");const {data,error}=await supabase.from("staff").insert(payloads).select("id,employee_no,name,designation,department,phone,email,joining_date,status");if(error)throw new Error(error.message);setRows(prev=>[...(data||[]),...prev]);setMsg((data?.length||0)+" staff records imported successfully.");}catch(e){setMsg("Import failed: "+(e instanceof Error?e.message:"Invalid CSV file"));}finally{setSaving(false);if(fileRef.current)fileRef.current.value=""}}
 async function handleImport(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(file)await importStaff(file)}
 async function toggle(r:StaffRow){const next=r.status==="active"?"inactive":"active";const {data,error}=await supabase.from("staff").update({status:next}).eq("id",r.id).select("id,employee_no,name,designation,department,phone,email,joining_date,status").single();if(error){setMsg("Could not update status: "+error.message);return}setRows(prev=>prev.map(x=>x.id===r.id?data:x));setMsg(r.name+" is now "+next+".")}
 const active=rows.filter(r=>r.status==="active").length; const teachers=rows.filter(r=>String(r.designation||"").toLowerCase().includes("teacher")&&r.status==="active").length;
 return <div><div className="cards"><div className="card"><div className="label">Total Staff</div><div className="value">{rows.length}</div></div><div className="card"><div className="label">Active Staff</div><div className="value">{active}</div></div><div className="card"><div className="label">Teachers</div><div className="value">{teachers}</div></div><div className="card"><div className="label">Inactive</div><div className="value">{rows.length-active}</div></div></div>
 <div className="card" style={{marginTop:16}}><div className="hero" style={{marginBottom:16}}><div><h2>{editingId?"Edit Staff":"Add Staff Member"}</h2><p className="muted">Maintain the school staff directory.</p></div>{editingId&&<button className="button" onClick={reset}>Cancel Edit</button>}</div><div className="form-grid">
 {[["Employee No.","employee_no"],["Name *","name"],["Designation","designation"],["Department","department"],["Phone","phone"],["Email","email"],["Joining Date","joining_date"]].map(([label,key])=><label className="field" key={key}><span>{label}</span><input type={key==="joining_date"?"date":"text"} value={(form as any)[key]} onChange={e=>setForm(x=>({...x,[key]:e.target.value}))}/></label>)}
 <label className="field"><span>Status</span><select value={form.status} onChange={e=>setForm(x=>({...x,status:e.target.value}))}><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div><div className="settings-actions"><button className="button primary" disabled={saving} onClick={save}>{saving?"Saving...":editingId?"Update Staff":"Add Staff"}</button>{msg&&<span className="save-message">{msg}</span>}</div></div>
 <div className="card" style={{marginTop:16,overflowX:"auto"}}><div className="hero" style={{marginBottom:12}}><div><h2>Staff Directory</h2><p className="muted">Search, import, edit and activate or deactivate staff.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="button" onClick={downloadTemplate}>Download Template</button><button className="button primary" disabled={saving} onClick={()=>fileRef.current?.click()}>Import CSV</button><input ref={fileRef} type="file" accept=".csv,text/csv" onChange={handleImport} style={{display:"none"}}/></div></div><div className="toolbar"><input placeholder="Search staff..." value={query} onChange={e=>setQuery(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All Status</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div><table className="data-table"><thead><tr><th>Staff</th><th>Employee No.</th><th>Designation</th><th>Department</th><th>Contact</th><th>Joining</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong>{r.name}</strong><div className="muted">{r.email||"—"}</div></td><td>{r.employee_no||"—"}</td><td>{r.designation||"—"}</td><td>{r.department||"—"}</td><td>{r.phone||"—"}</td><td>{r.joining_date||"—"}</td><td><span className="badge">{r.status}</span></td><td><button className="button" onClick={()=>edit(r)}>Edit</button>{" "}<button className="button" onClick={()=>toggle(r)}>{r.status==="active"?"Deactivate":"Activate"}</button></td></tr>)}</tbody></table>{!filtered.length&&<p className="muted">No staff records match your filters.</p>}</div></div>;
}
