"use client";
import{useMemo,useState}from"react";import{createClient}from"@/lib/supabase/client";
type School={id:string;name:string;slug:string;address?:string|null;city?:string|null;state?:string|null;phone?:string|null;email?:string|null;status:string;created_at:string};
type Plan={id:string;name:string;description?:string|null;monthly_price:number;annual_price:number;max_students:number|null;max_staff:number|null;features:Record<string,boolean>;is_active:boolean};
type Sub={id:string;school_id:string;plan_id:string;status:string;billing_cycle:string;trial_ends_at?:string|null;current_period_end?:string|null};
export default function SuperAdminClient({initialSchools,initialPlans,initialSubscriptions}:{initialSchools:School[];initialPlans:Plan[];initialSubscriptions:Sub[]}){
 const sb=createClient();const[schools,setSchools]=useState(initialSchools);const[plans,setPlans]=useState(initialPlans);const[subs,setSubs]=useState(initialSubscriptions);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
 const[schoolForm,setSchoolForm]=useState({id:"",name:"",slug:"",address:"",city:"",state:"",phone:"",email:""});const[planForm,setPlanForm]=useState({id:"",name:"",description:"",monthly:"0",annual:"0",students:"100",staff:"15",active:true});
 const subMap=useMemo(()=>new Map(subs.map(s=>[s.school_id,s])),[subs]);const planMap=useMemo(()=>new Map(plans.map(p=>[p.id,p])),[plans]);
 async function refresh(){const[{data:s},{data:p},{data:u}]=await Promise.all([sb.from("schools").select("id,name,slug,address,city,state,phone,email,status,created_at").order("created_at",{ascending:false}),sb.from("subscription_plans").select("id,name,description,monthly_price,annual_price,max_students,max_staff,features,is_active").order("monthly_price"),sb.from("subscriptions").select("id,school_id,plan_id,status,billing_cycle,trial_ends_at,current_period_end")]);setSchools((s??[]) as School[]);setPlans((p??[]) as Plan[]);setSubs((u??[]) as Sub[]);}
 async function run(fn:string,args:Record<string,unknown>){setBusy(true);setMessage("");const{error}=await sb.rpc(fn,args);setBusy(false);if(error){setMessage(error.message);return false}await refresh();setMessage("Saved successfully.");return true}
 async function saveSchool(e:React.FormEvent){e.preventDefault();const f=schoolForm;const ok=f.id?await run("super_admin_update_school",{p_school_id:f.id,p_name:f.name,p_slug:f.slug,p_address:f.address,p_city:f.city,p_state:f.state,p_phone:f.phone,p_email:f.email}):await run("super_admin_create_school",{p_name:f.name,p_slug:f.slug,p_address:f.address,p_city:f.city,p_state:f.state,p_phone:f.phone,p_email:f.email,p_academic_year_name:"2026-27",p_academic_year_start:"2026-04-01",p_academic_year_end:"2027-03-31"});if(ok)setSchoolForm({id:"",name:"",slug:"",address:"",city:"",state:"",phone:"",email:""});}
 async function savePlan(e:React.FormEvent){e.preventDefault();const f=planForm;const ok=await run("super_admin_upsert_plan",{p_plan_id:f.id||null,p_name:f.name,p_description:f.description,p_monthly_price:Number(f.monthly),p_annual_price:Number(f.annual),p_max_students:f.students?Number(f.students):null,p_max_staff:f.staff?Number(f.staff):null,p_features:{attendance:true,fees:true,homework:true,exams:true,reports:true,communication:true,parent_portal:true,student_portal:true},p_is_active:f.active});if(ok)setPlanForm({id:"",name:"",description:"",monthly:"0",annual:"0",students:"100",staff:"15",active:true});}
 function editSchool(s:School){setSchoolForm({id:s.id,name:s.name,slug:s.slug,address:s.address??"",city:s.city??"",state:s.state??"",phone:s.phone??"",email:s.email??""});window.scrollTo({top:0,behavior:"smooth"});}
 function editPlan(p:Plan){setPlanForm({id:p.id,name:p.name,description:p.description??"",monthly:String(p.monthly_price),annual:String(p.annual_price),students:p.max_students==null?"":String(p.max_students),staff:p.max_staff==null?"":String(p.max_staff),active:p.is_active});}
 const field=(label:string,value:string,onChange:(v:string)=>void,placeholder?:string)=><label style={{display:"grid",gap:6}}><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>;
 return <div>
  <div className="cards"><div className="card"><div className="label">Schools</div><div className="value">{schools.length}</div></div><div className="card"><div className="label">Active</div><div className="value">{schools.filter(s=>s.status==="active").length}</div></div><div className="card"><div className="label">Plans</div><div className="value">{plans.length}</div></div><div className="card"><div className="label">Subscriptions</div><div className="value">{subs.length}</div></div></div>
  {message&&<div className="card" style={{marginTop:16}}><strong>{message}</strong></div>}
  <div className="grid" style={{marginTop:16}}>
   <form className="card" onSubmit={saveSchool}><h2>{schoolForm.id?"Edit School":"Create School Tenant"}</h2><p className="muted">Create a fully initialized tenant with branding, settings, academic year and a Free trial subscription.</p><div className="grid" style={{gap:12}}>{field("School name",schoolForm.name,v=>setSchoolForm({...schoolForm,name:v}),"School name")}{field("Slug",schoolForm.slug,v=>setSchoolForm({...schoolForm,slug:v.toLowerCase().replace(/[^a-z0-9-]/g,"-")}),"school-name")}{field("Address",schoolForm.address,v=>setSchoolForm({...schoolForm,address:v}))}{field("City",schoolForm.city,v=>setSchoolForm({...schoolForm,city:v}))}{field("State",schoolForm.state,v=>setSchoolForm({...schoolForm,state:v}))}{field("Phone",schoolForm.phone,v=>setSchoolForm({...schoolForm,phone:v}))}{field("Email",schoolForm.email,v=>setSchoolForm({...schoolForm,email:v}))}</div><div style={{display:"flex",gap:8,marginTop:16,flexWrap:"wrap"}}><button className="button" disabled={busy}>{busy?"Saving…":schoolForm.id?"Update School":"Create School"}</button>{schoolForm.id&&<button type="button" className="button secondary" onClick={()=>setSchoolForm({id:"",name:"",slug:"",address:"",city:"",state:"",phone:"",email:""})}>Cancel</button>}</div></form>
   <form className="card" onSubmit={savePlan}><h2>{planForm.id?"Edit Plan":"Create Subscription Plan"}</h2><p className="muted">Plans control tenant limits and feature availability. Payment gateways are not used.</p><div className="grid" style={{gap:12}}>{field("Plan name",planForm.name,v=>setPlanForm({...planForm,name:v}),"Standard")}{field("Description",planForm.description,v=>setPlanForm({...planForm,description:v}))}{field("Monthly price",planForm.monthly,v=>setPlanForm({...planForm,monthly:v}))}{field("Annual price",planForm.annual,v=>setPlanForm({...planForm,annual:v}))}{field("Max students",planForm.students,v=>setPlanForm({...planForm,students:v}))}{field("Max staff",planForm.staff,v=>setPlanForm({...planForm,staff:v}))}</div><label style={{display:"flex",gap:8,alignItems:"center",marginTop:12}}><input type="checkbox" checked={planForm.active} onChange={e=>setPlanForm({...planForm,active:e.target.checked})}/> Plan active</label><div style={{display:"flex",gap:8,marginTop:16,flexWrap:"wrap"}}><button className="button" disabled={busy}>{busy?"Saving…":planForm.id?"Update Plan":"Create Plan"}</button>{planForm.id&&<button type="button" className="button secondary" onClick={()=>setPlanForm({id:"",name:"",description:"",monthly:"0",annual:"0",students:"100",staff:"15",active:true})}>Cancel</button>}</div></form>
  </div>
  <div className="card" style={{marginTop:16}}><h2>School Tenants</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>School</th><th>Location</th><th>Status</th><th>Plan</th><th>Subscription</th><th>Actions</th></tr></thead><tbody>{schools.map(s=>{const sub=subMap.get(s.id);const plan=sub?planMap.get(sub.plan_id):undefined;return <tr key={s.id}><td><strong>{s.name}</strong><div className="muted">{s.slug}</div></td><td>{s.city??""}{s.state?", "+s.state:""}</td><td><span className="badge">{s.status}</span></td><td>{plan?.name??"—"}</td><td>{sub?.status??"—"} · {sub?.billing_cycle??"—"}</td><td><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button className="button secondary" onClick={()=>editSchool(s)}>Edit</button><button className="button secondary" onClick={()=>run("super_admin_set_school_status",{p_school_id:s.id,p_status:s.status==="active"?"suspended":"active"})}>{s.status==="active"?"Suspend":"Activate"}</button><select value={sub?.plan_id??""} onChange={e=>e.target.value&&run("super_admin_assign_subscription",{p_school_id:s.id,p_plan_id:e.target.value,p_status:sub?.status==="suspended"?"active":(sub?.status??"active"),p_billing_cycle:sub?.billing_cycle??"monthly",p_trial_days:14})}><option value="">Change plan…</option>{plans.filter(p=>p.is_active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div></td></tr>})}</tbody></table></div></div>
  <div className="grid" style={{marginTop:16}}>{plans.map(p=><div className="card" key={p.id}><div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"center"}}><h3>{p.name}</h3><span className="badge">{p.is_active?"active":"inactive"}</span></div><p className="muted">{p.description??"No description"}</p><div className="row"><span>Monthly</span><strong>₹{Number(p.monthly_price).toLocaleString("en-IN")}</strong></div><div className="row"><span>Annual</span><strong>₹{Number(p.annual_price).toLocaleString("en-IN")}</strong></div><div className="row"><span>Limits</span><strong>{p.max_students??"∞"} students · {p.max_staff??"∞"} staff</strong></div><div style={{display:"flex",gap:8,marginTop:12}}><button className="button secondary" onClick={()=>editPlan(p)}>Edit</button><button className="button secondary" onClick={()=>run("super_admin_set_plan_active",{p_plan_id:p.id,p_is_active:!p.is_active})}>{p.is_active?"Deactivate":"Activate"}</button></div></div>)}</div>
 </div>
}