"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Row={student_id:string;name:string;admission_no:string|null;status:string};
type Opt={id:string;name:string};
export default function TeacherAttendanceClient({schoolId,staffId}:{schoolId:string;staffId:string}){
 const supabase=createClient(), [classes,setClasses]=useState<Opt[]>([]),[sections,setSections]=useState<Opt[]>([]),[classId,setClassId]=useState(""),[sectionId,setSectionId]=useState(""),[date,setDate]=useState(new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata"}).format(new Date())),[rows,setRows]=useState<Row[]>([]),[values,setValues]=useState<Record<string,string>>({}),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{(async()=>{const {data}=await supabase.from("teacher_assignments").select("class_id,section_id").eq("school_id",schoolId).eq("teacher_id",staffId);const cids=[...new Set((data??[]).map(x=>x.class_id))],sids=[...new Set((data??[]).map(x=>x.section_id))];const [{data:cs},{data:ss}]=await Promise.all([cids.length?supabase.from("classes").select("id,name").in("id",cids):Promise.resolve({data:[]}),sids.length?supabase.from("sections").select("id,name").in("id",sids):Promise.resolve({data:[]})]);setClasses(cs??[]);setSections(ss??[]);})();},[schoolId,staffId]);
 const load=async()=>{if(!classId||!sectionId)return;setLoading(true);setMsg("");const {data:students,error}=await supabase.from("students").select("id,name,admission_no").eq("school_id",schoolId).eq("class_id",classId).eq("section_id",sectionId).in("status",["active","admitted"]).order("name");if(error){setMsg(error.message);setLoading(false);return}const ids=(students??[]).map(s=>s.id);const {data:att}=ids.length?await supabase.from("student_attendance").select("student_id,status").eq("school_id",schoolId).eq("attendance_date",date).in("student_id",ids):{data:[]};const m=new Map((att??[]).map(x=>[x.student_id,x.status]));const rs=(students??[]).map(s=>({student_id:s.id,name:s.name,admission_no:s.admission_no,status:m.get(s.id)??"present"}));setRows(rs);setValues(Object.fromEntries(rs.map(x=>[x.student_id,x.status])));setLoading(false)};
 useEffect(()=>{load()},[classId,sectionId,date]);
 const counts=useMemo(()=>{const v=Object.values(values);return {present:v.filter(x=>x==="present").length,absent:v.filter(x=>x==="absent").length,late:v.filter(x=>x==="late").length,leave:v.filter(x=>x==="leave").length}},[values]);
 const save=async()=>{setSaving(true);setMsg("");const {data:{user}}=await supabase.auth.getUser();if(!user){setMsg("Session expired. Please login again.");setSaving(false);return}const payload=rows.map(r=>({school_id:schoolId,student_id:r.student_id,attendance_date:date,status:values[r.student_id]||"present",marked_by:user.id}));const {error}=await supabase.from("student_attendance").upsert(payload,{onConflict:"student_id,attendance_date"});setMsg(error?"Save failed: "+error.message:"Attendance saved successfully for "+rows.length+" students.");setSaving(false)};
 return <div className="content"><div className="hero"><div><h1>Student Attendance</h1><p className="muted">Mark attendance for your assigned classes.</p></div><span className="badge">Teacher Workspace</span></div><div className="card"><div className="form-grid"><label>Class<select value={classId} onChange={e=>{setClassId(e.target.value);setSectionId("")}}><option value="">Select class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Section<select value={sectionId} onChange={e=>setSectionId(e.target.value)}><option value="">Select section</option>{sections.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div></div><div className="cards"><div className="card"><div className="label">Present</div><div className="value">{counts.present}</div></div><div className="card"><div className="label">Absent</div><div className="value">{counts.absent}</div></div><div className="card"><div className="label">Late</div><div className="value">{counts.late}</div></div><div className="card"><div className="label">Leave</div><div className="value">{counts.leave}</div></div></div>{msg&&<div className="success" style={{margin:"12px 0"}}>{msg}</div>}<div className="card" style={{overflowX:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:8,marginBottom:12}}><h2>Students</h2><button className="button primary" disabled={saving||loading||!rows.length} onClick={save}>{saving?"Saving…":"Save Attendance"}</button></div>{!classId||!sectionId?<p className="muted">Select a class and section.</p>:loading?<p className="muted">Loading students…</p>:!rows.length?<p className="muted">No active students found.</p>:<table className="data-table"><thead><tr><th>Student</th><th>Admission No.</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.student_id}><td><strong>{r.name}</strong></td><td>{r.admission_no??"—"}</td><td><select value={values[r.student_id]||"present"} onChange={e=>setValues(v=>({...v,[r.student_id]:e.target.value}))}><option value="present">Present</option><option value="absent">Absent</option><option value="late">Late</option><option value="leave">Leave</option></select></td></tr>)}</tbody></table>}</div></div>
}