"use client";
import {useState} from "react";
import {createClient} from "@/lib/supabase/client";
type User={user_id:string;display_name:string|null;is_active:boolean;role_id:string|null;role_name:string|null;role_desc:string|null};
type Role={id:string;name:string;description:string|null};
const blank={employee_no:"",name:"",email:"",phone:"",designation:"",department:"",joining_date:"",password:""};
export default function UserRoleClient({schoolId,initialUsers,roles,currentUserId}:{schoolId:string;initialUsers:User[];roles:Role[];currentUserId:string}){
 const supabase=createClient(); const [users,setUsers]=useState(initialUsers); const [saving,setSaving]=useState<string|null>(null); const [msg,setMsg]=useState(""); const [form,setForm]=useState({...blank,role_id:roles.find(r=>r.name==="teacher")?.id??roles[0]?.id??""});
 const [creating,setCreating]=useState(false);
 async function createEmployee(){if(!form.name.trim()||!form.email.trim()||!form.password||!form.role_id){setMsg("Name, email, password and role are required.");return}if(form.password.length<8){setMsg("Password must be at least 8 characters.");return}setCreating(true);setMsg("");const {data,error}=await supabase.functions.invoke("create-school-employee",{body:{school_id:schoolId,...form}});if(error){setMsg("Could not create employee: "+error.message);setCreating(false);return}if(data?.error){setMsg("Could not create employee: "+data.error);setCreating(false);return}const role=roles.find(r=>r.id===form.role_id);setUsers(xs=>[{user_id:data.user_id,display_name:form.name,is_active:true,role_id:form.role_id,role_name:role?.name??null,role_desc:role?.description??null},...xs]);setForm({...blank,role_id:form.role_id});setMsg("Employee account and staff record created successfully.");setCreating(false)}
 async function changeRole(user:User,roleId:string){if(user.user_id===currentUserId&&user.role_name==="school_admin"){setMsg("Your own School Admin role cannot be changed here.");return}setSaving(user.user_id);setMsg("");const role=roles.find(r=>r.id===roleId);const {error}=await supabase.from("user_roles").update({role_id:roleId}).eq("user_id",user.user_id).eq("school_id",schoolId);if(error){setMsg("Could not change role: "+error.message);setSaving(null);return}setUsers(xs=>xs.map(x=>x.user_id===user.user_id?{...x,role_id:roleId,role_name:role?.name??null,role_desc:role?.description??null}:x));setMsg("Role updated successfully.");setSaving(null)}
 async function toggle(user:User){if(user.user_id===currentUserId){setMsg("Your own account cannot be deactivated here.");return}setSaving(user.user_id);const {error}=await supabase.from("school_users").update({is_active:!user.is_active}).eq("user_id",user.user_id).eq("school_id",schoolId);if(error){setMsg("Could not update account: "+error.message);setSaving(null);return}setUsers(xs=>xs.map(x=>x.user_id===user.user_id?{...x,is_active:!x.is_active}:x));setMsg("Account status updated.");setSaving(null)}
 const employeeRoles=roles.filter(r=>r.name!=="super_admin");
 return <div><div className="cards"><div className="card"><div className="label">School Users</div><div className="value">{users.length}</div></div><div className="card"><div className="label">Active</div><div className="value">{users.filter(x=>x.is_active).length}</div></div><div className="card"><div className="label">Inactive</div><div className="value">{users.filter(x=>!x.is_active).length}</div></div><div className="card"><div className="label">Roles Available</div><div className="value">{employeeRoles.length}</div></div></div>
 <div className="card" style={{marginTop:16}}><h2>➕ Add Employee / Create Login</h2><p className="muted">Create one employee account, staff record and role assignment together.</p><div className="form-grid">
 {([["Employee ID","employee_no"],["Full Name *","name"],["Login Email *","email"],["Phone","phone"],["Designation","designation"],["Department","department"],["Joining Date","joining_date"],["Temporary Password *","password"]] as const).map(([label,key])=><label className="field" key={key}><span>{label}</span><input type={key==="joining_date"?"date":key==="password"?"password":key==="email"?"email":"text"} value={form[key]} onChange={e=>setForm(x=>({...x,[key]:e.target.value}))}/></label>)}
 <label className="field"><span>Employee Role *</span><select value={form.role_id} onChange={e=>setForm(x=>({...x,role_id:e.target.value}))}>{employeeRoles.map(r=><option key={r.id} value={r.id}>{r.description||r.name}</option>)}</select></label></div><div className="settings-actions"><button className="button primary" disabled={creating} onClick={createEmployee}>{creating?"Creating...":"Create Employee Login"}</button></div></div>
 <div className="card" style={{marginTop:16}}><h2>User & Role Management</h2><p className="muted">Manage existing school accounts and permissions.</p>{msg&&<div className="success" style={{marginTop:12}}>{msg}</div>}<div className="table-wrap"><table className="data-table"><thead><tr><th>User</th><th>User ID</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{users.map(u=><tr key={u.user_id}><td><strong>{u.display_name||"Unnamed user"}</strong>{u.user_id===currentUserId&&<div className="muted">Current account</div>}</td><td style={{fontSize:12}}>{u.user_id}</td><td><select value={u.role_id||""} disabled={saving===u.user_id||u.user_id===currentUserId&&u.role_name==="school_admin"} onChange={e=>changeRole(u,e.target.value)}>{employeeRoles.map(r=><option key={r.id} value={r.id}>{r.description||r.name}</option>)}</select></td><td><span className="badge">{u.is_active?"active":"inactive"}</span></td><td><button className="button" disabled={saving===u.user_id||u.user_id===currentUserId} onClick={()=>toggle(u)}>{u.is_active?"Deactivate":"Activate"}</button></td></tr>)}</tbody></table></div></div>
 <div className="card" style={{marginTop:16}}><h2>Role Access</h2><div className="grid" style={{gridTemplateColumns:"repeat(2,minmax(0,1fr))"}}>{employeeRoles.map(r=><div className="row" key={r.id}><div><strong>{r.description||r.name}</strong><div className="muted">{r.name}</div></div><span className="badge">{users.filter(u=>u.role_id===r.id).length} users</span></div>)}</div></div></div>;
}