"use client";
import { useEffect,useState } from "react";
import { createClient } from "@/lib/supabase/client";
export default function ResetPasswordPage(){
 const sb=createClient(); const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[ready,setReady]=useState(false),[session,setSession]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{sb.auth.getSession().then(({data})=>{setSession(!!data.session);setReady(true)});const{data}=sb.auth.onAuthStateChange((_e,s)=>{setSession(!!s);setReady(true)});return()=>data.subscription.unsubscribe()},[]);
 async function send(){setMsg("");if(!email){setMsg("Enter your email.");return}const{error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+"/reset-password"});setMsg(error?error.message:"Password reset link sent. Check your email.");}
 async function update(){setMsg("");if(password.length<8||password!==confirm){setMsg("Passwords must match and be at least 8 characters.");return}const{error}=await sb.auth.updateUser({password});if(error)setMsg(error.message);else setMsg("Password updated. You can now sign in.");}
 return <main className="auth-page"><div className="auth-card"><div className="brand-mark">🔐</div><h1>{session?"Set New Password":"Reset Password"}</h1><p className="muted">{session?"Choose a new password for your account.":"Enter your account email and we will send a secure reset link."}</p>{ready&&session?<form onSubmit={e=>{e.preventDefault();update()}}><label>New Password<input required type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirm Password<input required type="password" minLength={8} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button>Update Password</button></form>:<form onSubmit={e=>{e.preventDefault();send()}}><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button>Send Reset Link</button></form>}{msg&&<div className={msg.includes("sent")||msg.includes("updated")?"success":"error"} style={{marginTop:12}}>{msg}</div>}<a className="muted" href="/login">← Back to Login</a></div></main>
}